NLP-UG-2023-24/Jolki_Palki_WebDev_Project

index.html
Another attempt at the sam thing #blessed
=> add basic html elements

index.html
let's see how it goes, shall we? ;)
=> add about me section

index.html
=> small correction

index.html
=> add provisional github icons

style_sheet.css
this is a bit of a test, just looking what may happen :P
=> create flex display of box and person classes

index.html, style_sheet.css
making some changes... I had a little rouble earlier but all's good ;)
=> change name of div

index.html
ok i think this is the last one tonight
=> connect css to index

test.html
i did somethingg. (it's just a loose suggestion 👼 )
=> first attempt to create a website

index.html
=> added beautiful colors

index.html, style_sheet.css
zmieniłam kolorki i wreszcie news podświetla się w kolorze!!
=> switch colors

style_sheet.css
=> update and fix css

index.html
=> Update news tab

style_sheet.css
=> another changes for news tab

index.html
=> change button font

rabbitrunner.html, script.js
I hope it'll work this time. It took me sooo much time to figure it out, so it better be worth it.
=> connecting rabbitrunner to index

style_sheet.css
=> change font of about headers into pixel

index.html, style_sheet.css
=> reposition title and logo above buttons - final try

script.js
I found a code that should prevent a potential user from choosing future date. 
But... I'm not sure about its placement...
=> fixed choosing date

index.html, style_sheet.css
=> made stylistic changes

rabbitrunner.html
=> second attempt to add space to jump

index.html, style_sheet.css
I reorganised the whole file and added comments with Tab names :) 
It goes in an identical order of elements as in the HTML file 
I was just TOO lost at one point XD
=> organise css file

index.html, script.js, style_sheet.css
after 2 days I managed to do something like that. I hope it'll work properly. 
No dark mode yet. ;(
=> 1st attempt to introduce accessibility

style_sheet.css
=> some changes in high contrast mode

index.html, style_sheet.css
=> add thought bubble

style_sheet.css
=> ate a bracket sorry

style_sheet.css
=> center instruction containers in mobile view

index.html, style_sheet.css
- Bunny page-positioning fixed
- Footer issue solved
- Menu responsiveness fixed
Fingers Crossed it all works well now :))
P.S.: Home tab Bunny still to be fixed (in the making....)
=> updated layout: bunny, footer, menu responsive adjustments
